### ISSUE TITLE
Dropdown and button example

### ISSUE THREAD

**Issue by Codeize** [OtterDevelopment/typescript-discord-boilerplate#1]
I see there is classes for Dropdown and button support.

Would it be too much to ask to have a working example of these in the boilerplate?

If not, all good.

**Comment by xPolar** [comment]
Will do this once I have free time.

**Comment by Codeize** [comment]
I don't assume you happen to have had any free time?

**Comment by xPolar** [comment]
I can commit a simple button roles example in a little bit, currently trying to focus on my school though.

**Comment by Codeize** [comment]
Fair enough, just wanted to check if you forgot about this.
But there isn't a rush on this whatsoever, naturally IRL stuff comes before this.

**Comment by Codeize** [comment]
I figured this out a month or two ago, so just to notify you, you can close this issue, however maybe others would benefit from a working example in this repo.

**Comment by idk-pixel** [comment]
For me the bot it self does not work.

**Comment by xPolar** [comment]
Are you having any errors @idk-pixel?
